### ISSUE TITLE
[Not a bug] Cydia error "subprocess new pre-removal script returned error exit status 126" (iOS 11)

### ISSUE THREAD

**Issue by mademanof06** [angelXwind/AppSync#32]
Not able to have any tweaks 
Error code
Sub-process/use/libexec/cydia/cydo returned an error code (1)
 Any help would be greatly appreciated!

**Comment by angelXwind** [comment]
It appears that you are experiencing the "subprocess new pre-removal script returned error exit status 126" error.

Please note that you are only running into this error because you have installed AppSync Unified from a **third-party piracy-centered repo.**

In order to avoid future incidents, please always make sure that you are installing the official version from my Cydia/APT repo, https://cydia.angelxwind.net/

To fix this issue and restore the use of Cydia, SSH into your device as `root` and run the following commands:

```
echo -e '#!/bin/sh\nexit 0' > /var/lib/dpkg/info/net.angelxwind.appsyncunified.postinst
echo -e '#!/bin/sh\nexit 0' > /var/lib/dpkg/info/net.angelxwind.appsyncunified.prerm
chmod +x /var/lib/dpkg/info/net.angelxwind.appsyncunified.postinst
chmod +x /var/lib/dpkg/info/net.angelxwind.appsyncunified.prerm
```

If this does not work, it is possible that you have installed an AppSync Unified package that has a bundle ID different from mine. In that case, replace `net.angelxwind.appsyncunified` with whatever bundle ID you see in Cydia (for instance, `repo.biteyourapple.net.appsyncunified` which is another piracy mirror known to break iOS 11 if installed).

**Comment by mademanof06** [comment]
Is it possible you can upgrade your program (appsync unified) to run with 11.3.1?

**Comment by tihiandrew** [comment]
how can we change the bundle name ?

**Comment by mademanof06** [comment]
Tihiandrew~ are you able to install or remove any tweaks? If I were to remove this jailbreak start over and use Electra once again do you know if we would be in the same situation?

**Comment by tihiandrew** [comment]
no, seems that i can install tweaks , the appear as installed but no tweak is working . still get that 126 error

**Comment by mademanof06** [comment]
OK so I just found out I was able to download apps/tweaks but of course they don’t work. I tried using M terminal downloaded from the Karen repo it tells me it needs to be updated on their end. Also I cleaner pro (crashes) If I try to remove an old tweak, appsync unified needs to be upgraded. I can add repos, even then it’s still asking or needing to install apps sync unified (iPhones-arm) no matter if I remove or install I still get the error code (1)
I believe Karen’s repo needs to upgrade appssync unified both versions11.3.x and upgrade 8.2. 
Come on Karen’s repo you can do it!!
