### ISSUE TITLE
Installation of any IPAs fails

### ISSUE THREAD

**Issue by OBEY-T** [angelXwind/AppSync#35]
Can't install using Filza/iFunBox.

I had installed a tweak from BiteYourApple but have removed it since, issues still persists. I am installing ASU from the official repo.

**Comment by angelXwind** [comment]
If you can install an unsigned IPA like the PPSSPP's (http://build.ppsspp.org/?page/downloads#ios), then this is not an issue with AppSync Unified, but rather whatever tool created the IPA you are attempting to install.

The vast majority of IPAs created by fakesigning or "cracking" tools are broken on iOS 11 due to missing the `platform-application` entitlement. This is a limitation of Electra/KPPLess (although, apparently plans exist to work around this in Electra 1.1).

**Comment by OBEY-T** [comment]
Thanks for the reply, I worked out that the problem was due to an incorrect symlink of /Library/TweakInject, which was initially a symlink to /Library/MobileSubstrate/DynamicLibraries. It is supposed to be a symlink to /usr/lib/TweakInject instead, and once I had corrected this symlink ASU worked fine.

It seems that other tweaks would function fine with the incorrect symlink but I noticed ASU did not as I had tried to install the PPSSPP IPA and it still did not work. The issue was not related to the BYA repo.

**Comment by abelyi100** [comment]
First of all, thanks a lot for your reply!
The installation of PPSSPP succeeded.
But I don’t quite get that, because I can’t even install any “properly signed” IPAs I download directly with iTunes.
I know I might be wrong, but how can this happen?  So what you mean is, even those IPAs on the app store may not have the “platform-application” entitlement.  Is that right?

Furthermore, in a Taiwanese forum.  I even see someone successfully install an modified IPA on iOS 11.3.1 with only “Payload” folder inside.(He extracts the app from /var/containers/Bundle/Application and zip it directly). Not sure if this thing matters, just to mention it.
