### ISSUE TITLE
Phoenix bug

### ISSUE THREAD

**Issue by serjepatoff** [angelXwind/AppSync#39]
Not actually an issue, but a question. What Phoenix bug asu_inject fights with?

**Comment by angelXwind** [comment]
This is explained in AppSync Unified 90.0's improved packaging code, but I'll explain here too.

https://www.reddit.com/r/jailbreak/comments/lhod33/update_appsync_unified_900_massive_rewrite_of/

Basically, due to some strange bug in Phœnix, the `asu_inject` LaunchDaemon (which launches `/usr/bin/asu_inject` once upon boot) is required in order to properly inject AppSync Unified into installd after a reboot.

No idea why, but on Phœnix devices, if you reboot without running `asu_inject`, AppSync Unified will just… never be injected into `installd` for some bizarre reason.
