### ISSUE TITLE
Can no longer install anything as of today.

### ISSUE THREAD

**Issue by JEmlay** [angelXwind/AppSync#55]
I find it very coincidentale that this is happening right now today at the same time Apple made a change on their end that broke Impactor, ReProvision and anything having to do to with dev accounts.

Is it possible Appsync is getting tripped up by this same issue:

"Please update to Xcode 7.3 or later to continue developing with your Apple ID."

???

**Comment by aswathraja** [comment]
I guess it could be fixed by the same changes done on the issue for ReProvision. I have tested their new experimental and apps are signing and installing successfully. 

iPhone 6S
iOS 12.4

@angelXwind  Please refer the issue and the attached PR below

https://github.com/Matchstic/ReProvision/issues/96

**Comment by JEmlay** [comment]
Same here.  With the beta it's working again.  Both signing and installing.
